# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Steno & PL
description: |-
  This is a personal blog. Unless otherwise stated, the opinions
  expressed here are my own, and not those of my past or present
  employers.
real_name: Waleed Khan
email: me@waleedkhan.name
url: "https://blog.waleedkhan.name" # the base hostname & protocol for your site
github_username: arxanas
google_analytics_id: 'UA-53066274-1'
permalink: none

# Build settings
markdown: kramdown

plugins:
  - jekyll-katex
  - jekyll-twitter-plugin

katex:
  rendering_options:
    throw_error: true                       # throwOnError - set to false if you want rendering to output error as text rather than a build error
