[settings]
# Read from `.ruby-version`
# See: https://mise.jdx.dev/configuration.html#idiomatic-version-files
idiomatic_version_file_enable_tools = ["ruby"]

[tools]
actionlint = "1.7.7"

[tasks.build]
depends = ["setup"]
run = "bundle exec jekyll build"

[tasks.lint]
run = "actionlint"

[tasks.setup]
outputs = { auto = true }
run = "bundle install"
sources = [".ruby-version", "Gemfile", "Gemfile.lock"]

[tasks.watch]
depends = ["setup"]
run = "bundle exec jekyll serve --drafts --incremental"
