[tools]
actionlint = "1.7.7"
node = "26.2.0"
ruby = "3.4.9"

[tasks.build]
depends = ["setup"]
run = "bundle exec jekyll build"

[tasks.lint]
run = "actionlint"

[tasks.setup]
outputs = { auto = true }
run = "bundle install"
sources = ["Gemfile", "Gemfile.lock"]

[tasks.watch]
depends = ["setup"]
run = "bundle exec jekyll serve --drafts --incremental"
