## Copied from https://github.com/actions/jekyll-build-pages
name: Publish site

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Github Pages
        uses: actions/configure-pages@v3

      - name: Build Jekyll site
        uses: actions/jekyll-build-pages@v1

      - name: Upload Github Pages artifact
        uses: actions/upload-pages-artifact@v1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy site to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
